/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdministrativeRole;

import Schema.Enterprise.Enterprise;
import javax.swing.JPanel;

/**
 *
 * @author 16176
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel() {
        initComponents();
    }

    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLbl = new javax.swing.JLabel();
        enterpriseLbl = new javax.swing.JLabel();
        valueLbl = new javax.swing.JLabel();
        manageOrgBtn = new javax.swing.JButton();
        manageEmpBtn = new javax.swing.JButton();
        manageUserBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        headerLbl.setText("My Work Area - Administrative Role");
        add(headerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        enterpriseLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        enterpriseLbl.setText("Enterprise:");
        add(enterpriseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        valueLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        valueLbl.setText("<value>");
        add(valueLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        manageOrgBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manageOrgBtn.setText("Manage Organization");
        add(manageOrgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 260, -1));

        manageEmpBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manageEmpBtn.setText("Manage Employee");
        add(manageEmpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 260, -1));

        manageUserBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manageUserBtn.setText("Manage User");
        add(manageUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 260, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLbl;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JButton manageEmpBtn;
    private javax.swing.JButton manageOrgBtn;
    private javax.swing.JButton manageUserBtn;
    private javax.swing.JLabel valueLbl;
    // End of variables declaration//GEN-END:variables
}
